image: sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.9.4_2.13.11

services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  SBT_OPTS: "-Xmx1G"

stages:
  - build
  - test

before_script:
  - sbt clean update

build:
  stage: build
  script:
    - sbt "scalafmtCheckAll; compile"

test:
  stage: test
  script:
    - export DOCKER_HOST="tcp://docker:2375"
    - sbt "project integration_tests" IntegrationTest/test

