image: sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.9.4_2.13.11

stages:
  - build
  - test

before_script:
  - sbt clean update

build:
  stage: build
  script:
    - sbt "scalafmtCheckAll; compile"

test:
  stage: test
  script:
    - echo "Enable Docker to run integration tests..."
#    - sbt "project integration_tests" IntegrationTest/test

