image: sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.9.4_2.13.11

TC_CLOUD_TOKEN: "aj_tcc_svc_Ng8FUmMDrzsr8LNC6kADcaUXxewyVCMKsJye2FMsHh74c"

stages:
  - build
  - test

before_script:
  - sbt clean update

build:
  stage: build
  script:
    - sbt "scalafmtCheckAll; compile"

test:
  stage: test
  script:
  - curl -fsSL https://app.testcontainers.cloud/bash | bash
    - sbt "project integration_tests" IntegrationTest/test

