services:
  - name: docker:dind
    command: ["--tls=false"]
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  SBT_OPTS: "-Xmx1G"


image: sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.9.4_2.13.11

stages:
  - build
  - test

before_script:
  - sbt clean update

build:
  stage: build
  script:
    - sbt "scalafmtCheckAll; compile"

test:
  stage: test
  script:
    - sbt "project integration_tests" IntegrationTest/test

