version: '3.8'

services:
  app:
    image: docker.io/library/project:0.1.0-SNAPSHOT
    environment:
      DB_URL: db
      DB_USER: postgres
      DB_PASS: pass1234
      DB_NAME: event_store
      KAFKA_SERVER: kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
